networks:
  default:

services:
  # Collect logs from Dokku apps
  vector:
    restart: unless-stopped
    image: timberio/vector:0.43.1-debian
    volumes:
      - ./configs/vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/dokku/apps:/var/log/dokku/apps
    ports:
      - "8686:8686"
    networks:
      - default
    depends_on:
      - loki

  loki:
    restart: unless-stopped
    image: grafana/loki:3.5.0
    volumes:
      - /docker_data/loki:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  grafana:
    restart: unless-stopped
    image: grafana/grafana:11.6.1
    environment:
      - "GF_SMTP_ENABLED=true"
      - "GF_SMTP_HOST=smtp.gmail.com:587"
      - "GF_SMTP_USER=server.rokaskasperavicius@gmail.com"
      - "GF_SMTP_PASSWORD=${SMTP_PASSWORD}"
      - "GF_SMTP_FROM_ADDRESS=server.rokaskasperavicius@gmail.com"
    volumes:
      - /docker_data/grafana/:/var/lib/grafana
      - ./configs/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    networks:
      - default
    env_file:
      - .env

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:v3.3.0
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker_data/prometheus:/prometheus
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - default
  # Exporter for Pi-hole metrics
  pihole-exporter:
    restart: unless-stopped
    image: ekofr/pihole-exporter:latest
    environment:
      PIHOLE_HOSTNAME: "192.168.1.7"
      PIHOLE_PASSWORD: "1a9016e6d2b4e220c7daae5a4b383bb6"
      PIHOLE_PORT: "1080"
      PORT: "9617"
    ports:
      - "9617:9617"
    networks:
      - default
