networks:
  default:

services:
  # vector:
  #   restart: always
  #   image: timberio/vector:0.43.1-debian
  #   volumes:
  #     - ./configs/vector.yaml:/etc/vector/vector.yaml:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/log/dokku/apps:/var/log/dokku/apps
  #   ports:
  #     - "8686:8686"
  #   networks:
  #     - default
  #   depends_on:
  #     - loki

  loki:
    restart: always
    image: grafana/loki:latest
    volumes:
      - /docker_data/loki:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  grafana:
    restart: always
    image: grafana/grafana:latest
    environment:
      - "GF_SMTP_ENABLED=true"
      - "GF_SMTP_HOST=smtp.gmail.com:587"
      - "GF_SMTP_USER=server.rokaskasperavicius@gmail.com"
      - "GF_SMTP_PASSWORD=${SMTP_PASSWORD}"
      - "GF_SMTP_FROM_ADDRESS=server.rokaskasperavicius@gmail.com"
    volumes:
      - /docker_data/grafana/:/var/lib/grafana
      - ./configs/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    networks:
      - default
    env_file:
      - .env

  # For linux logs
  # promtail:
  #   restart: always
  #   image: grafana/promtail:latest
  #   volumes:
  #     - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml
  #   networks:
  #     - default

  # Other metrics
  prometheus:
    restart: always
    image: prom/prometheus
    volumes:
      # - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker_data/prometheus:/prometheus
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - default
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh

  # For system metrics
  # node_exporter:
  #   restart: always
  #   image: prom/node-exporter
  #   ports:
  #     - "9100:9100"
  #   networks:
  #     - default

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./configs/config.alloy:/etc/alloy/config.alloy:ro
      - /docker_data/alloy:/var/lib/alloy/data
    ports:
      - "12345:12345"
    networks:
      - default
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
