networks:
  default:

services:
  vector:
    image: timberio/vector:0.43.1-debian
    volumes:
      - ./configs/vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/dokku/apps:/var/log/dokku/apps
    ports:
      - "8686:8686"
    networks:
      - default
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    volumes:
      - /docker_data/loki:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    environment:
      - "GF_SMTP_ENABLED=true"
      - "GF_SMTP_HOST=smtp.gmail.com:587"
      - "GF_SMTP_USER=server.rokaskasperavicius@gmail.com"
      - "GF_SMTP_PASSWORD=${SMTP_PASSWORD}"
      - "GF_SMTP_FROM_ADDRESS=server.rokaskasperavicius@gmail.com"
    volumes:
      - /docker_data/grafana/:/var/lib/grafana
      - ./configs/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    networks:
      - default
    env_file:
      - .env

  # For linux logs
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - default

  # Other metrics
  prometheus:
    image: prom/prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker_data/prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - default

  # For system metrics
  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - default
