apiVersion: 1

datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    isDefault: true
    access: proxy
    version: 1
    editable: false
    basicAuth: false
  
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: false
    access: proxy
    editable: false