sources:
  docker-global-source:
    type: docker_logs
    include_labels:
      - com.dokku.app-name

transforms:
  flatten_labels:
    type: remap
    inputs: ["docker-global-source"]
    source: |
      .app_name = get!(., ["label", "com.dokku.app-name"])
      .time = now()
      del(.label)

sinks:
  docker-global-sink:
    inputs:
      - flatten_labels
    type: loki
    endpoint: http://loki:3100
    encoding:
      codec: json
    labels:
      app: "{{ app_name }}"
  console_out:
    type: console
    inputs:
      - flatten_labels
    encoding:
      codec: json
